<a href="https://colab.research.google.com/github/XuRui314/MathematicalModeling/blob/main/Multivariate_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# preparation
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


## PCA

## 案例1
对重庆市城镇居民人均消费数据的分析，消费包括视频、衣着、家庭设备用品、医疗保险、交通通信、文教娱乐、居住、杂项商品、服务这8个方面，给定的是从1997年到2006年这10年的数据。

In [ ]:
import os
os.chdir("/content/drive/MyDrive/dataset/MathModel/PCA")
!ls

data12_1.txt  data12_2.txt  data12_3.xlsx  data12_5_1.txt  data12_5_2.xlsx


In [ ]:
import numpy as np
import pandas as pd
from sklearn.decomposition import PCA
from scipy.stats import zscore

In [ ]:
data = np.loadtxt('data12_1.txt') # 纯数据文件，可以采用np.loadtxt
print(data)

[[2297.86  589.62  474.74  164.19  290.91  626.21  295.2   199.03]
 [2262.19  571.69  461.25  185.9   337.83  604.78  354.66  198.96]
 [2303.29  589.99  516.21  236.55  403.92  730.05  438.41  225.8 ]
 [2308.7   551.14  476.45  293.23  406.44  785.74  494.04  254.1 ]
 [2337.65  589.28  509.82  334.05  442.5   850.15  563.72  246.51]
 [2418.96  618.6   454.2   429.6   615.   1065.12  594.48  164.28]
 [2702.34  735.01  475.36  459.69  790.26 1025.99  741.6   187.81]
 [3015.32  779.68  474.15  537.95  865.45 1200.52  903.22  196.77]
 [3135.65  849.53  583.5   629.32  929.92 1391.11  882.41  221.85]
 [3415.92 1038.98  615.74  705.72  976.02 1449.49  954.56  242.26]]


In [ ]:
data = pd.read_csv('data12_1.txt',sep='\t', header=None) # 也可以用pandas来读txt

In [ ]:
data

0        1       2       3       4        5       6       7
0  2297.86   589.62  474.74  164.19  290.91   626.21  295.20  199.03
1  2262.19   571.69  461.25  185.90  337.83   604.78  354.66  198.96
2  2303.29   589.99  516.21  236.55  403.92   730.05  438.41  225.80
3  2308.70   551.14  476.45  293.23  406.44   785.74  494.04  254.10
4  2337.65   589.28  509.82  334.05  442.50   850.15  563.72  246.51
5  2418.96   618.60  454.20  429.60  615.00  1065.12  594.48  164.28
6  2702.34   735.01  475.36  459.69  790.26  1025.99  741.60  187.81
7  3015.32   779.68  474.15  537.95  865.45  1200.52  903.22  196.77
8  3135.65   849.53  583.50  629.32  929.92  1391.11  882.41  221.85
9  3415.92  1038.98  615.74  705.72  976.02  1449.49  954.56  242.26

In [ ]:
data = data.values
print(data)

[[2297.86  589.62  474.74  164.19  290.91  626.21  295.2   199.03]
 [2262.19  571.69  461.25  185.9   337.83  604.78  354.66  198.96]
 [2303.29  589.99  516.21  236.55  403.92  730.05  438.41  225.8 ]
 [2308.7   551.14  476.45  293.23  406.44  785.74  494.04  254.1 ]
 [2337.65  589.28  509.82  334.05  442.5   850.15  563.72  246.51]
 [2418.96  618.6   454.2   429.6   615.   1065.12  594.48  164.28]
 [2702.34  735.01  475.36  459.69  790.26 1025.99  741.6   187.81]
 [3015.32  779.68  474.15  537.95  865.45 1200.52  903.22  196.77]
 [3135.65  849.53  583.5   629.32  929.92 1391.11  882.41  221.85]
 [3415.92 1038.98  615.74  705.72  976.02 1449.49  954.56  242.26]]


In [ ]:
norm = zscore(data, ddof=1) # 数据标准化
print(norm)

[[-0.76076777 -0.64214522 -0.54059347 -1.25096611 -1.19811321 -1.14171193
  -1.38154326 -0.507142  ]
 [-0.84506173 -0.75532164 -0.78862442 -1.13462085 -1.01960322 -1.21228148
  -1.13035357 -0.50955582]
 [-0.7479358  -0.63980973  0.22188565 -0.8631843  -0.76815981 -0.79976409
  -0.77655041  0.41596886]
 [-0.7351511  -0.88503583 -0.50915293 -0.5594326  -0.75857232 -0.61637547
  -0.54154062  1.39183877]
 [-0.66673758 -0.64429134  0.10439731 -0.34067564 -0.62137986 -0.40427165
  -0.24717639  1.13011253]
 [-0.47458894 -0.4592198  -0.91824771  0.17138284  0.03490684  0.30363019
  -0.1172303  -1.70542749]
 [ 0.19508369  0.2755748  -0.52919398  0.33263705  0.70169414  0.17477407
   0.5042804  -0.89404166]
 [ 0.93470589  0.55753748 -0.55144138  0.75203733  0.98775905  0.74950593
   1.18704657 -0.58507366]
 [ 1.21906508  0.99843949  1.45909859  1.24169493  1.23303908  1.37712379
   1.09913441  0.27976087]
 [ 1.88138828  2.1942718   2.05187233  1.65112735  1.40842932  1.56937065
   1.40393319  0.

In [ ]:
model = PCA().fit(norm) # 构造并拟合模型
print('特征值是：\n', model.explained_variance_)
print('各主成分贡献率：\n', model.explained_variance_ratio_)

特征值是：
 [6.27943341e+00 1.30599080e+00 2.74277611e-01 9.97624700e-02
 2.31016993e-02 1.22233669e-02 4.69357480e-03 5.17066158e-04]
各主成分贡献率：
 [7.84929176e-01 1.63248850e-01 3.42847014e-02 1.24703088e-02
 2.88771241e-03 1.52792086e-03 5.86696851e-04 6.46332697e-05]


In [ ]:
xs1 = model.components_
print('各主成分系数：\n',xs1) # 就是协方差矩阵特征向量矩阵

各主成分系数：
 [[ 0.39186166  0.38439344  0.3059243   0.39231584  0.38537825  0.38961322
   0.38389911  0.05908768]
 [ 0.0210478  -0.02214509 -0.47783697  0.08905605  0.19878256  0.1043221
   0.11376475 -0.83634169]
 [-0.14762176 -0.39254883 -0.57745685  0.20021017  0.15914777  0.1347164
   0.4303164   0.47108809]
 [-0.47832186 -0.48941314  0.44488132  0.27708115 -0.02393188  0.46564673
  -0.07989617 -0.18222681]
 [-0.09762149 -0.27604773  0.34873203 -0.35508891  0.52307577 -0.45643408
   0.4158212  -0.10824944]
 [-0.70552867  0.53549607 -0.049896    0.32914209  0.14716623 -0.28505603
   0.02367193  0.03426265]
 [-0.08102349  0.10492282  0.11905975 -0.07206231 -0.68369188 -0.02060535
   0.68706375 -0.15212634]
 [ 0.28557308 -0.29011082  0.09180137  0.6940343  -0.15286467 -0.55886444
  -0.05098258 -0.07665729]]


In [ ]:
check = xs1.sum(axis = 1, keepdims=True) # 计算各个主成分系数和
xs2 = xs1*np.sign(check) # 和为负数的话就乘以-1
print('调整后的主成分系数：\n',xs2)

调整后的主成分系数：
 [[ 0.39186166  0.38439344  0.3059243   0.39231584  0.38537825  0.38961322
   0.38389911  0.05908768]
 [-0.0210478   0.02214509  0.47783697 -0.08905605 -0.19878256 -0.1043221
  -0.11376475  0.83634169]
 [-0.14762176 -0.39254883 -0.57745685  0.20021017  0.15914777  0.1347164
   0.4303164   0.47108809]
 [ 0.47832186  0.48941314 -0.44488132 -0.27708115  0.02393188 -0.46564673
   0.07989617  0.18222681]
 [ 0.09762149  0.27604773 -0.34873203  0.35508891 -0.52307577  0.45643408
  -0.4158212   0.10824944]
 [-0.70552867  0.53549607 -0.049896    0.32914209  0.14716623 -0.28505603
   0.02367193  0.03426265]
 [ 0.08102349 -0.10492282 -0.11905975  0.07206231  0.68369188  0.02060535
  -0.68706375  0.15212634]
 [-0.28557308  0.29011082 -0.09180137 -0.6940343   0.15286467  0.55886444
   0.05098258  0.07665729]]
