<a href="https://colab.research.google.com/github/XuRui314/MathematicalModeling/blob/main/Python_used_for_Mathematical_Modeling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy

### Linear Algebra

In [ ]:
import numpy as np

In [ ]:
# 求范数
a = np.array([[0,3,4],[1,6,4]])
b = np.linalg.norm(a, axis = 1)
c = np.linalg.norm(a, axis = 0)
d = np.linalg.norm(a)
print('行向量2范数为：', np.round(b, 4)) # np.round是四舍五入，第二个参数的保留的小数位数
print('列向量2范数为：', np.round(c, 4))
print('矩阵2范数为：', np.round(d, 4))

行向量2范数为： [5.     7.2801]
列向量2范数为： [1.     6.7082 5.6569]
矩阵2范数为： 8.8318


In [ ]:
# 解方程组 Ax=b
a = np.array([[3,1],[1,2]])
b = np.array([9,8])
x1 = np.linalg.inv(a) @ b # 写法1
print(x1)
x2 = np.linalg.solve(a,b) # 写法2
print(x2)

[2. 3.]
[2. 3.]


In [ ]:
# 求超定线性方程组的最小二乘解
a = np.array([[3,1],[1,2],[1,1]])
b = np.array([9,8,6])
x = np.linalg.pinv(a) @ b
print(np.round(x, 4))

[2.     3.1667]


In [ ]:
# 求特征值、特征向量
a = np.eye(4)
b = np.rot90(a)
c,d = np.linalg.eig(b)

# 求svd分解 补充资料：https://www.cnblogs.com/xym4869/p/11301727.html
u,sigma,vT = np.linalg.svd(b)
print('特征值为：', c)
print('特征向量为：\n', d)
print(u)
print(sigma)
print(vT)

特征值为： [ 1. -1.  1. -1.]
特征向量为：
 [[ 0.70710678  0.70710678  0.          0.        ]
 [ 0.          0.          0.70710678 -0.70710678]
 [ 0.          0.          0.70710678  0.70710678]
 [ 0.70710678 -0.70710678  0.          0.        ]]
[[ 0.  0.  0. -1.]
 [ 0.  0. -1.  0.]
 [ 0. -1.  0.  0.]
 [-1.  0.  0.  0.]]
[1. 1. 1. 1.]
[[-1. -0. -0. -0.]
 [-0. -1. -0. -0.]
 [-0. -0. -1. -0.]
 [-0. -0. -0. -1.]]


## Pandas

In [ ]:
list("ABCD")

['A', 'B', 'C', 'D']

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
dates = pd.date_range(start = '20220705', end = '20220714', freq = 'D')
a1 = pd.DataFrame(np.random.randn(10,4), index = dates, columns = list('ABCD')) # np.random.rand用法https://blog.csdn.net/u012149181/article/details/78913167
a2 = pd.DataFrame(np.random.rand(10,4))

In [ ]:
a1

A         B         C         D
2022-07-05  1.841288  0.059626  0.442391  0.525836
2022-07-06 -0.025731 -0.131777 -0.025393 -0.157042
2022-07-07  0.272290  0.330645 -0.701684  0.086323
2022-07-08 -0.001569 -0.793649  1.318828 -2.545351
2022-07-09 -0.137085 -1.040567  0.374049  0.894863
2022-07-10  1.493263 -0.044269 -0.441630 -0.373912
2022-07-11  0.509658 -0.708353  2.468572  1.950335
2022-07-12  0.101423  0.267396 -0.848440  0.168649
2022-07-13 -0.040581 -0.541435 -0.439659 -0.661300
2022-07-14 -0.504384  0.541569  0.180633  0.586825

In [ ]:
a2

0         1         2         3
0  0.540855  0.839390  0.908594  0.102230
1  0.592235  0.024538  0.322185  0.229403
2  0.872174  0.217103  0.961040  0.524242
3  0.244244  0.626698  0.568797  0.450015
4  0.215156  0.927071  0.918650  0.650074
5  0.269469  0.848291  0.039820  0.858876
6  0.607935  0.175491  0.610379  0.056694
7  0.588520  0.113374  0.014278  0.809902
8  0.897219  0.473335  0.425949  0.973528
9  0.513102  0.908854  0.074982  0.149108

## SciPy

In [ ]:
# 求非线性方程解
from scipy.optimize import fsolve, root
fx = lambda x:     x**980-5.01*x**979+7.398*x**978\
    -3.388*x**977-x**3+5.01*x**2-7.398*x+3.388
x1 = fsolve(fx, 1.5, maxfev=4000)  #函数调用4000次
x2 = root(fx, 1.5)
print(x1,'\n','-------------'); print(x2)

[1.21] 
 -------------
    fjac: array([[-1.]])
     fun: array([-1.23341756e+69])
 message: 'The solution converged.'
    nfev: 319
     qtf: array([2.00183544e+72])
       r: array([2.54210657e+80])
  status: 1
 success: True
       x: array([1.21])


In [ ]:
# 求非线性方程组解
fx = lambda x: [x[0]**2+x[1]**2-1, x[0]-x[1]]
s1 = fsolve(fx, [1, 1])
s2 = root(fx, [1, 1])
print(s1,'\n','--------------'); print(s2)

[0.70710678 0.70710678] 
 --------------
    fjac: array([[-0.81649679, -0.57734998],
       [ 0.57734998, -0.81649679]])
     fun: array([4.4408921e-16, 0.0000000e+00])
 message: 'The solution converged.'
    nfev: 9
     qtf: array([-3.64625238e-10,  2.57828785e-10])
       r: array([-1.73205167, -0.57735171,  1.63299357])
  status: 1
 success: True
       x: array([0.70710678, 0.70710678])


## SymPy

## Matplotlib